### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by EliotBerriot** [jshmrtn/vue3-gettext#1]
Hi, I just wanted to thank you for porting `vue-gettext` to Vue 3. I've integrated in a project of mine this morning and it seem to works exactly as expected. I didn't observe any regression compared to the original `vue-gettext` package used on a Vue 2 app.

So, kudos and thank you :pray: :pray: :pray: 

(Feel free to close this of course ;)

**Comment by lzurbriggen** [comment]
@EliotBerriot Seems like I missed this issue. The package hasn't seen that much use yet, so thank you for letting us know!
