### ISSUE TITLE
Use vue-demi for vue 2 compatibility

### ISSUE THREAD

**Issue by wvffle** [jshmrtn/vue3-gettext#25]
I'm currently migrating a big project that uses `vue-gettext` from vue 2 to vue 3. If there would be an option for `vue3-gettext` to use `vue-demi` internally, it'd be much easier for me to migrate.

**Comment by lzurbriggen** [comment]
Hello @wvffle, I have experimented with vue-demi in the past and I don't think it would be quite that easy to achieve full compatibility. I also don't really want to have to do extra testing and maintaintenance.

I have migrated a couple projects myself, and the effort required was minimal. What you could try would be to use [@jshmrtn/vue3-gettext](https://www.npmjs.com/package/@jshmrtn/vue3-gettext) (version 1, much closer to the original `vue-gettext`) and then later migrate to the newer [vue3-gettext](https://www.npmjs.com/package/vue3-gettext) (version 2) if you want to.
