### ISSUE TITLE
Possible to add translator comments?

### ISSUE THREAD

**Issue by simensol** [jshmrtn/vue3-gettext#28]
Is it possible to add translator comments to `$gettext` (and the other functions), which appear in the extracted `po` file?

**Comment by Knogobert** [comment]
I would use `$pgettext` to get some sort of context for the string and not have collaboration comments pushed to the code/repository history. I would instead use a service like [POEditor](https://poeditor.com) to collaborate via comments.

To me this is out of scope for the package. I wish you best of luck!

**Comment by simensol** [comment]
Actually, I agree. I think I have been a little confused about the purpose of context vs. comments in `gettext`. Thanks for clearing things up!
