### ISSUE TITLE
Multiple messages in one HTML node are not extracted

### ISSUE THREAD

**Issue by matyasrichter** [jshmrtn/vue3-gettext#29]
Not sure if this is a `vue3-gettext` issue or a `gettext-extractor` issue, but it seems that for HTML nodes containing multiple messages, only the first message is extracted.
For example:
```
<span>
  {{ $gettext("Message 1") }}
  <br>
  {{ $gettext("Message 2") }}
</span>
```

When running `npm run gettext:extract`, the output .po file only contains "Message 1".

**Comment by lzurbriggen** [comment]
@matyasrichter I just release `2.3.4` to fix this issue, please let me know if you still experience issues.
