### ISSUE TITLE
vue-gettext-extract: "Error: Command failed: find ..."

### ISSUE THREAD

**Issue by alexshink** [jshmrtn/vue3-gettext#3]
Hello! First of all, thanks for your work.

### What is the problem?

Executing `vue-gettext-extract` command results in error:
```
Error: Command failed: find ./src/components -name '*.js' -o -name '*.vue' 2> /dev/null
```

But an empty `locales` directory is created in `src` directory.

Details in the screenshot:
![image](https://user-images.githubusercontent.com/27574860/106195434-b7422280-61e2-11eb-8bda-39f06521fd1a.png)

### How to reproduce the problem

In a clean project created via `@vue/cli` after installing `@jshmrtn/vue3-gettext`, in `package.json` add the line in the `scripts` section:
```
"gettext:extract": "vue-gettext-extract --src ./src/components --out ./src/locales --locales \"ru_RU,en_US\""
```

At the command line, run the command `gettext:extract`.

### Environment

Windows 10
Vue 3.0.0
@vue/cli 4.5.10
@jshmrtn/vue3-gettext 1.0.1

**Comment by lzurbriggen** [comment]
@alexshink Sorry, this is not documented properly, the scripts rely on some command-line tools that are not available on Windows, like `find`, and the GNU gettext utilities (for example `msgmerge`). I recommend trying to execute the scripts in a UNIX-like environment on Windows like git-bash, WSL, WSL2, MINGW or Cygwin.

I'll close this for now as I don't see a way to make the scripts compatible with native Windows.

**Comment by astarrh** [comment]
Hey! It would be really great to have this mentioned in the docs, as it took a good hour for me to find out here that Windows isn't supported!
