### ISSUE TITLE
Read languages from LINGUAS file

### ISSUE THREAD

**Issue by georgkrause** [jshmrtn/vue3-gettext#30]
Currently when running `vue-gettext-extract` or `vue-gettext-compile` only languages specified in `gettext.config.js` are processed. It would be nice if I could configure to read the LINGUAS file and process all languages specified in there.

**Comment by lzurbriggen** [comment]
@georgkrause I don't really like to potentially have multiple configuration sources and then have to think about config priority or diverging lists. I honestly don't really see the point but if you *really really* want this and implement it in a PR I would consider merging it.

**Comment by georgkrause** [comment]
@lzurbriggen Sorry for the late reply! I tend to agree, several locations are usually source of confusion. But in this case we are able to write out the languages to a LINGUAS file, which can be read by translation tools. Those are also able to write into LINGUAS in case a new translation was added. Currently there is no way in vue3-gettext to update the translations based on those additions, which feels like a feature gap. Does it change your mind?
