### ISSUE TITLE
use vue-gettext-extract on typescript files

### ISSUE THREAD

**Issue by underdoeg** [jshmrtn/vue3-gettext#4]
Is there a way toe extract translations from typescript *.ts files?

**Comment by lzurbriggen** [comment]
@underdoeg This was an oversight. I added `.ts` files to the extract script and created release `1.1.0`. I plan to make this more flexible/configurable in the future.

Please let me know if this works for you!

**Comment by underdoeg** [comment]
That was quick.

I think it works on your side but I think easygettext doesn't like my generated typescript file.

```
 could not read: './src/api/generated/apigen.ts' using acorn as parser
Trace: TypeError: Cannot read property 'type' of undefined
```

An exclude config would be nice now because this file doesn't include any translations. But I think we can close this issue.

**Comment by lzurbriggen** [comment]
@underdoeg I'll find a solution for this, but it may take a while. I wanted to implement configuration files and make `easygettext` (that we use for extraction) fully configurable.

For now you could just copy and adjust [gettext_extract.js](https://github.com/jshmrtn/vue3-gettext/blob/master/scripts/gettext_extract.js#L45) to fit your use case, it's a bit messy but not super complex.
