### ISSUE TITLE
Cosmiconfig version upgrade

### ISSUE THREAD

**Issue by cpontvieux-systra** [jshmrtn/vue3-gettext#53]
Sorry @lzurbriggen, @jshmrtn , the latest release is not enough to read ESM config module: `cosmiconfig` should be updated to version `9.0.0`.

I see there is a pull request which drops `cosmiconfig` in favor of `lilconfig`. I cannot comment on it, but if the result is an ESM config module readable, then that’s ok.

I don’t know when this would be ready though. BTW, if you need help and/or testing, I’m available as I use your project a lot at work.

**Comment by lzurbriggen** [comment]
@cpontvieux-systra no worries.

> I see there is a pull request which drops cosmiconfig in favor of lilconfig.

that pull request won't be ready for a while, but yes, the ultimate goal is to have proper ESM compatibility and phase out CommonJS eventually. unfortunately we are very busy at the moment and can't justify putting a lot of work into this right now (and we _generally_ consider vue3-gettext feature complete).

if you could open a pull request with the updated cosmiconfig and test it properly, that would be great!
